version: '3.3'
services:
  app:
    build: .
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8000:8000'
    expose:
      # Opens port 3306 on the container
      - '8000'
    environment:
      PYTHONUNBUFFERED: 1
      MYSQL_HOST: 'dbserver'
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      DATASOURCE: 'MYSQL' # Choose between MYSQL and REDIS

      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_DATABASE: 0
    restart: always
    depends_on:
      - dbserver
      - cache

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./src/datasources/redis/redis-dump:/data

  dbserver:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./src/datasources/mysql/mysql-dump:/docker-entrypoint-initdb.d

  app-test:
    build: .
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8001:8000'
    expose:
      # Opens port 3306 on the container
      - '8001'
    environment:
      PYTHONUNBUFFERED: 1
      MYSQL_HOST: 'dbserver-test'
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      DATASOURCE: 'MYSQL' # Choose between MYSQL and REDIS
    restart: always
    depends_on:
      - dbserver-test

  dbserver-test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db-test:/var/lib/mysql
      - ./src/datasources/mysql/mysql-dump:/docker-entrypoint-initdb.d
#    command: mysqld --init-file="/docker-entrypoint-initdb.d/dump.sql"
# Names our volume
volumes:
  my-db:
  my-db-test:
  cache: